/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace BrimdexFeeds {
  export type PriceDataStruct = {
    price: BigNumberish;
    timestamp: BigNumberish;
    roundId: BigNumberish;
    decimals: BigNumberish;
  };

  export type PriceDataStructOutput = [
    price: bigint,
    timestamp: bigint,
    roundId: bigint,
    decimals: bigint
  ] & { price: bigint; timestamp: bigint; roundId: bigint; decimals: bigint };
}

export interface BrimdexFeedsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allFeedIds"
      | "feedExists"
      | "feedNames"
      | "feeds"
      | "getAllFeedIds"
      | "getFeed"
      | "getFeedByName"
      | "getFeedCount"
      | "getFeedId"
      | "getFeeds"
      | "getFeedsByName"
      | "owner"
      | "registerFeed"
      | "transferOwnership"
      | "updateFeedByName"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "FeedRegistered" | "FeedUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allFeedIds",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "feedExists",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "feedNames",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "feeds", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getAllFeedIds",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getFeed", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "getFeedByName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedCount",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getFeedId", values: [string]): string;
  encodeFunctionData(
    functionFragment: "getFeeds",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getFeedsByName",
    values: [string[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerFeed",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateFeedByName",
    values: [string, BigNumberish, BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "allFeedIds", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feedExists", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feedNames", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "feeds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getAllFeedIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFeed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeedByName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFeedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getFeedId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFeeds", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getFeedsByName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerFeed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateFeedByName",
    data: BytesLike
  ): Result;
}

export namespace FeedRegisteredEvent {
  export type InputTuple = [feedId: BytesLike, feedName: string];
  export type OutputTuple = [feedId: string, feedName: string];
  export interface OutputObject {
    feedId: string;
    feedName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FeedUpdatedEvent {
  export type InputTuple = [
    feedId: BytesLike,
    feedName: string,
    price: BigNumberish,
    timestamp: BigNumberish,
    roundId: BigNumberish,
    decimals: BigNumberish
  ];
  export type OutputTuple = [
    feedId: string,
    feedName: string,
    price: bigint,
    timestamp: bigint,
    roundId: bigint,
    decimals: bigint
  ];
  export interface OutputObject {
    feedId: string;
    feedName: string;
    price: bigint;
    timestamp: bigint;
    roundId: bigint;
    decimals: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface BrimdexFeeds extends BaseContract {
  connect(runner?: ContractRunner | null): BrimdexFeeds;
  waitForDeployment(): Promise<this>;

  interface: BrimdexFeedsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allFeedIds: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  feedExists: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  feedNames: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  feeds: TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        roundId: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;

  getAllFeedIds: TypedContractMethod<[], [string[]], "view">;

  getFeed: TypedContractMethod<
    [feedId: BytesLike],
    [BrimdexFeeds.PriceDataStructOutput],
    "view"
  >;

  getFeedByName: TypedContractMethod<
    [feedName: string],
    [BrimdexFeeds.PriceDataStructOutput],
    "view"
  >;

  getFeedCount: TypedContractMethod<[], [bigint], "view">;

  getFeedId: TypedContractMethod<[feedName: string], [string], "view">;

  getFeeds: TypedContractMethod<
    [feedIds: BytesLike[]],
    [BrimdexFeeds.PriceDataStructOutput[]],
    "view"
  >;

  getFeedsByName: TypedContractMethod<
    [feedNameArray: string[]],
    [BrimdexFeeds.PriceDataStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerFeed: TypedContractMethod<[feedName: string], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  updateFeedByName: TypedContractMethod<
    [
      feedName: string,
      price: BigNumberish,
      roundId: BigNumberish,
      decimals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allFeedIds"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "feedExists"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "feedNames"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "feeds"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [
      [bigint, bigint, bigint, bigint] & {
        price: bigint;
        timestamp: bigint;
        roundId: bigint;
        decimals: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAllFeedIds"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getFeed"
  ): TypedContractMethod<
    [feedId: BytesLike],
    [BrimdexFeeds.PriceDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedByName"
  ): TypedContractMethod<
    [feedName: string],
    [BrimdexFeeds.PriceDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFeedId"
  ): TypedContractMethod<[feedName: string], [string], "view">;
  getFunction(
    nameOrSignature: "getFeeds"
  ): TypedContractMethod<
    [feedIds: BytesLike[]],
    [BrimdexFeeds.PriceDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFeedsByName"
  ): TypedContractMethod<
    [feedNameArray: string[]],
    [BrimdexFeeds.PriceDataStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerFeed"
  ): TypedContractMethod<[feedName: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateFeedByName"
  ): TypedContractMethod<
    [
      feedName: string,
      price: BigNumberish,
      roundId: BigNumberish,
      decimals: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "FeedRegistered"
  ): TypedContractEvent<
    FeedRegisteredEvent.InputTuple,
    FeedRegisteredEvent.OutputTuple,
    FeedRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "FeedUpdated"
  ): TypedContractEvent<
    FeedUpdatedEvent.InputTuple,
    FeedUpdatedEvent.OutputTuple,
    FeedUpdatedEvent.OutputObject
  >;

  filters: {
    "FeedRegistered(bytes32,string)": TypedContractEvent<
      FeedRegisteredEvent.InputTuple,
      FeedRegisteredEvent.OutputTuple,
      FeedRegisteredEvent.OutputObject
    >;
    FeedRegistered: TypedContractEvent<
      FeedRegisteredEvent.InputTuple,
      FeedRegisteredEvent.OutputTuple,
      FeedRegisteredEvent.OutputObject
    >;

    "FeedUpdated(bytes32,string,int256,uint64,uint80,uint8)": TypedContractEvent<
      FeedUpdatedEvent.InputTuple,
      FeedUpdatedEvent.OutputTuple,
      FeedUpdatedEvent.OutputObject
    >;
    FeedUpdated: TypedContractEvent<
      FeedUpdatedEvent.InputTuple,
      FeedUpdatedEvent.OutputTuple,
      FeedUpdatedEvent.OutputObject
    >;
  };
}
