/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BrimdexFeeds } from "./BrimdexFeeds";
export * as factories from "./factories";
export { BrimdexFeeds__factory } from "./factories/BrimdexFeeds__factory";
